spring.application.name=FFLmanager

anthropic.api.key=l

spring.datasource.url=es
spring.datasource.username=postgres
spring.datasource.password=l
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
